version: "3.3"
services:
  node:
    image: "node:alpine"
    container_name: "linguo-bot"
    user: "node"
    build: .
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: "npm run start"
